/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReseauRouteImport } from './routes/reseau'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as CarrieresRouteImport } from './routes/carrieres'
import { Route as IndexRouteImport } from './routes/index'

const ReseauRoute = ReseauRouteImport.update({
  id: '/reseau',
  path: '/reseau',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrieresRoute = CarrieresRouteImport.update({
  id: '/carrieres',
  path: '/carrieres',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrieres': typeof CarrieresRoute
  '/profil': typeof ProfilRoute
  '/reseau': typeof ReseauRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrieres': typeof CarrieresRoute
  '/profil': typeof ProfilRoute
  '/reseau': typeof ReseauRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrieres': typeof CarrieresRoute
  '/profil': typeof ProfilRoute
  '/reseau': typeof ReseauRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carrieres' | '/profil' | '/reseau'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carrieres' | '/profil' | '/reseau'
  id: '__root__' | '/' | '/carrieres' | '/profil' | '/reseau'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrieresRoute: typeof CarrieresRoute
  ProfilRoute: typeof ProfilRoute
  ReseauRoute: typeof ReseauRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reseau': {
      id: '/reseau'
      path: '/reseau'
      fullPath: '/reseau'
      preLoaderRoute: typeof ReseauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrieres': {
      id: '/carrieres'
      path: '/carrieres'
      fullPath: '/carrieres'
      preLoaderRoute: typeof CarrieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrieresRoute: CarrieresRoute,
  ProfilRoute: ProfilRoute,
  ReseauRoute: ReseauRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
