/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReseauRouteImport } from './routes/reseau'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MbtiRouteImport } from './routes/mbti'
import { Route as CarrieresRouteImport } from './routes/carrieres'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const ReseauRoute = ReseauRouteImport.update({
  id: '/reseau',
  path: '/reseau',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MbtiRoute = MbtiRouteImport.update({
  id: '/mbti',
  path: '/mbti',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrieresRoute = CarrieresRouteImport.update({
  id: '/carrieres',
  path: '/carrieres',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrieres': typeof CarrieresRoute
  '/mbti': typeof MbtiRoute
  '/messages': typeof MessagesRoute
  '/profil': typeof ProfilRoute
  '/reseau': typeof ReseauRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrieres': typeof CarrieresRoute
  '/mbti': typeof MbtiRoute
  '/messages': typeof MessagesRoute
  '/profil': typeof ProfilRoute
  '/reseau': typeof ReseauRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrieres': typeof CarrieresRoute
  '/mbti': typeof MbtiRoute
  '/messages': typeof MessagesRoute
  '/profil': typeof ProfilRoute
  '/reseau': typeof ReseauRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrieres'
    | '/mbti'
    | '/messages'
    | '/profil'
    | '/reseau'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrieres'
    | '/mbti'
    | '/messages'
    | '/profil'
    | '/reseau'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/carrieres'
    | '/mbti'
    | '/messages'
    | '/profil'
    | '/reseau'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CarrieresRoute: typeof CarrieresRoute
  MbtiRoute: typeof MbtiRoute
  MessagesRoute: typeof MessagesRoute
  ProfilRoute: typeof ProfilRoute
  ReseauRoute: typeof ReseauRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reseau': {
      id: '/reseau'
      path: '/reseau'
      fullPath: '/reseau'
      preLoaderRoute: typeof ReseauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mbti': {
      id: '/mbti'
      path: '/mbti'
      fullPath: '/mbti'
      preLoaderRoute: typeof MbtiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrieres': {
      id: '/carrieres'
      path: '/carrieres'
      fullPath: '/carrieres'
      preLoaderRoute: typeof CarrieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CarrieresRoute: CarrieresRoute,
  MbtiRoute: MbtiRoute,
  MessagesRoute: MessagesRoute,
  ProfilRoute: ProfilRoute,
  ReseauRoute: ReseauRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
